version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: study_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: study
      MYSQL_USER: study_user
      MYSQL_PASSWORD: study_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: study_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: study_user
      DB_PASSWORD: study_password
      DB_NAME: study
    volumes:
      - .:/app
    working_dir: /app

volumes:
  mysql_data:
